CC = gcc
LIBS = -lpthread

all: ejercicio6B

ejercicio6B: ejercicio6B.c ejercicio6B_2.c
	$(CC) -o ejercicio6B ejercicio6B.c $(LIBS)
	$(CC) -o ejercicio6B_2 ejercicio6B_2.c $(LIBS)

clean:
	rm -rf ejercicio6B ejercicio6B_2
