CC = gcc
LIBS = -lpthread

all: ejercicio6D

ejercicio6D: ejercicio6D1.c ejercicio6D2.c
	$(CC) -o ejercicio6D1 ejercicio6D1.c $(LIBS)
	$(CC) -o ejercicio6D2 ejercicio6D2.c $(LIBS)

clean:
	rm -rf ejercicio6D1 ejercicio6D2
